### ISSUE TITLE
Add Zenodo DOI

### ISSUE THREAD

**Issue by alexdaniel654** [UKRIN-MAPS/ukat#138]
[Zenodo](https://zenodo.org/) is used by quite a few different academic packages to generate DOI for each software release to make referencing easier for people. Would be good to add it here.

**Comment by JSousa-UoL** [comment]
@plaresmedima can help us on this if needed as he has past experience with Zenodo

**Comment by alexdaniel654** [comment]
I've set it so the first DOI will be minted when we next do a release. v0.2.0 isn't far away so should get to test it then.
