### ISSUE TITLE
Update usage of arraystats in unwrapping experiment

### ISSUE THREAD

**Issue by fnery** [UKRIN-MAPS/ukat#95]
The [unwrapping](https://github.com/UKRIN-MAPS/ukat/tree/master/experiments/unwrapping) experiment still uses an old version of [`arraystats`](https://github.com/UKRIN-MAPS/ukat/blob/master/experiments/unwrapping/arraystats.py). This should be removed and [`unwrapping.py`](https://github.com/UKRIN-MAPS/ukat/blob/6a58d43f554673c7d78a08eca267504373e95e43/experiments/unwrapping/unwrapping.py) updated to use the new version of `arraystats` (`ukat.utils.arraystats`) once it is merged.

**Comment by JSousa-UoL** [comment]
This has been done a long time ago actually. Closing.
